### ISSUE TITLE
libtensorflowlite.so not found

### ISSUE THREAD

**Issue by sirramin** [nyadla-sys/whisper.tflite#22]
I tried to build android app but got below error:

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libtensorflowlite.so" not found: needed by /data/app/~~jOedJbF-1DUjS_rJaBhjHw==/com.whispertflite-1l5LPHQ3KSPQexsn0qsQjg==/base.apk!/lib/arm64-v8a/libaudioEngine.so in namespace clns-4
 at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
 at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
 at java.lang.System.loadLibrary(System.java:1661)
 at com.whispertflite.engine.WhisperEngineNative.<clinit>(WhisperEngineNative.java:66)
 at com.whispertflite.asr.Whisper.<init>(Whisper.java:32)
 at com.whispertflite.MainActivity.onCreate(MainActivity.java:152)
 at android.app.Activity.performCreate(Activity.java:8163)
 at android.app.Activity.performCreate(Activity.java:8130)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8319)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)`

**Comment by vilassn** [comment]
On which mobile device you are running this app? What is the processor architecture?

**Comment by vilassn** [comment]
We have added prebuilt tflite libs for below architecture.
arm64-v8a
armeabi-v7a
x86_64

**Comment by sirramin** [comment]
it's a Xiaomi note 9 pro that has arm64-v8a architecture

**Comment by vilassn** [comment]
Are you able to run whisper asr apk from release folder on your device properly?

**Comment by sirramin** [comment]
Yes It works fine.

**Comment by vilassn** [comment]
Please check your build environment. It can be due to ndk configuration or some other problem.

**Comment by RiyaAggarwal3008** [comment]
hey are u able to sole the above error on build?
