### ISSUE TITLE
Android app: Transcribe error

### ISSUE THREAD

**Issue by jdwdevs** [nyadla-sys/whisper.tflite#9]
First of all thank you for the sample app, but I'm getting "ByteBuffer is not a valid TensorFlow Lite model flatbuffer" from the application on every transcribe. Do let me know if there's any more information that you need to debug.

java.lang.IllegalArgumentException: ByteBuffer is not a valid TensorFlow Lite model flatbuffer
                 	at org.tensorflow.lite.NativeInterpreterWrapper.createModelWithBuffer(Native Method)
                 	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:71)
                 	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
                 	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:227)
                 	at com.example.tfliteaudio.TFLiteEngine.loadModel(TFLiteEngine.java:70)
                 	at com.example.tfliteaudio.TFLiteEngine.initialize(TFLiteEngine.java:32)
                 	at com.example.tfliteaudio.TranscriptionThread.run(TranscriptionThread.java:60)

**Comment by vilassn** [comment]
Model files .tfite are tracked with git lfs. Please check whether .tflite model file in asset file has valid size. If its size is 0 bytes, please perform git lfs install and then clone the repo.

**Comment by jdwdevs** [comment]
Thank you so much. It's working fine now.
